name: Publish

on:
  workflow_dispatch:
    branches:
      - main

env:
  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - run: curl -sSL https://install.python-poetry.org | python3 -

      - run: poetry install

      - run: poetry build

      - run: poetry publish
